# Generated by Django 5.2.2 on 2025-06-06 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=10, unique=True, verbose_name='ラインID')),
                ('name', models.CharField(max_length=100, verbose_name='ライン名')),
                ('x_position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='X座標')),
                ('y_position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Y座標')),
                ('width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='横幅')),
                ('height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='縦幅')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ライン',
                'verbose_name_plural': 'ライン',
                'ordering': ['line_id'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10, unique=True, verbose_name='機械ID')),
                ('name', models.CharField(max_length=100, verbose_name='機械名')),
                ('status', models.CharField(choices=[('active', '稼働中'), ('maintenance', 'メンテナンス中'), ('stopped', '停止中')], default='stopped', max_length=20, verbose_name='ステータス')),
                ('x_position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='X座標')),
                ('y_position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Y座標')),
                ('width', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='横幅')),
                ('height', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='縦幅')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('alarm_message', models.CharField(blank=True, max_length=200, verbose_name='アラームメッセージ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': '加工機',
                'verbose_name_plural': '加工機',
                'ordering': ['machine_id'],
            },
        ),
    ]
