# Generated by Django 5.2.2 on 2025-06-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='id',
        ),
        migrations.AlterField(
            model_name='line',
            name='line_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ラインID'),
        ),
    ]
