# Generated by Django 5.2.2 on 2025-06-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_remove_line_id_alter_line_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='機械ID'),
        ),
    ]
