# Generated by Django 5.2.2 on 2025-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_remove_machine_id_alter_machine_machine_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['id'], 'verbose_name': 'ライン', 'verbose_name_plural': 'ライン'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['id'], 'verbose_name': '加工機', 'verbose_name_plural': '加工機'},
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_id',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='line',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='設備名'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('active', '稼働中'), ('maintenance', 'メンテナンス中'), ('stopped', '停止中')], default='stopped', max_length=20, verbose_name='稼働状態'),
        ),
    ]
