# Generated by Django 5.2.2 on 2025-06-16 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_alter_line_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'ライン', 'verbose_name_plural': 'ライン'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-active', 'line__name', 'name'], 'verbose_name': '加工機', 'verbose_name_plural': '加工機'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='height',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='縦幅'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='横幅'),
        ),
    ]
