# Generated by Django 5.2.2 on 2025-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('cpu', models.FloatField(default=0, verbose_name='CPU使用率')),
                ('memory', models.FloatField(default=0, verbose_name='メモリ使用率')),
                ('disk', models.FloatField(default=0, verbose_name='ディスク使用率')),
            ],
            options={
                'verbose_name': 'リソース',
                'verbose_name_plural': 'リソース',
                'ordering': ['-created_at'],
            },
        ),
    ]
